### ISSUE TITLE
DBweek2 HW

### ISSUE THREAD

**Issue by KalpanaHYF** [zenkaeser/hyf-homework#5]
Insert query syntax error, plz correct it.
Plz put in comments the Qno for the relevant answered query.
Good work. keep it up.

**Comment by zenkaeser** [comment]
Hello Kalpana, I have implemented the feedback.
My insert query works just fine. It might be that you already have the ID 36, which was explicitly indicated to my query. I have changed it now so it works with auto increment and I don't need to explicitly assign a value. Hope it is okay now.
Thanks!
